### PR TITLE
Feature: integrate mini cart

### PR DESCRIPTION
**Pull request by willopez**
Impact: minor
Type: feature

## Summary
Integrates `MiniCart` component that will be rendered on hover over the cart icon. Further, clicking on the cart icon will result in the user being taken to the cart page.

## Testing
1. Hover over cart icon and verify mini cart is rendered
2. Click on cart icon and verify user is taken to the cart page.

### CODE REVIEW

**Comment by willopez** [comment]
@rymorgan not clear on what is the intended UX for the mini cart being displayed on hover. Do you have an example of another site that uses the experience we want?

**Comment by rymorgan** [comment]
Here are two good examples of mini carts -- 
https://www.target.com/ (without the page going dark) or https://www.bhphotovideo.com/ - also you'll notice that both go to the full page cart onclick.

**Comment by willopez** [comment]
@rymorgan Got it, thanks.

**Comment by willopez** [comment]
@nnnnat ready for another review.

**Comment by willopez** [comment]
@nnnnat @rymorgan updated the UX to hide the mini cart when mouse leaves mini cart.

**Comment by willopez** [comment]
@rymorgan @nnnnat I have created an issues in the component library to address incorrect font styles. https://github.com/reactioncommerce/reaction-component-library/issues/167 

Merging this in, as the font styles issues will be resolved when that issue is resolved.

**Pull request merged**
