### PR TITLE
Reaction Project Hooks

### PR DESCRIPTION
**Pull request by ticean**
Issue: none
Impact: minor
Type: chore

## Issue

We have two projects, `reaction` and `reaction-next-starterkit` that must be coordinated to run together. Keycloak will add a 3rd project and another Docker network. 

Create tooling that will configure and launch the projects with a single CLI command.

## Solution

Integrate this project with multi-project orchestration.

This PR adds everything needed to hook the project into the [reaction-next](https://github.com/reactioncommerce/reaction-next) meta project. All the existing backends and frontends can be launched with the `make` command. 

After this merge, `make` command in [reaction-next](https://github.com/reactioncommerce/reaction-next) launches:

* Meteor
* Devserver
* Reaction Next Starter Kit
* Keycloak

All user defined networks are automatically created.

See the [reactioncommerce/reaction-next](https://github.com/reactioncommerce/reaction-next) project README for more details.

### What's included

* A `bin/setup` script that will copy `.env.example` to `.env` in this project directory
* A `pre-build` project hook will run the bin/setup script to ensure the required `.env` file is in place before attempting to run Docker on the project.

## Testing

You can test reaction-next in a new directory to launch everything in complete isolation.

1. Install [reaction-next prequisites](https://github.com/reactioncommerce/reaction-next#prerequisites). Ensure you have SSH enabled on Github.
2. Ensure all Docker containers are stopped to avoid port conflicts.
2. `git clone git@github.com:reactioncommerce/reaction-next.git`
3. `make`
4. Expect a failure until this PR is merged. Check out this branch in `reaction-next-starterkit` (in the reaction-next folder):  
  `cd reaction-next-starterkit && git checkout -b reaction-project-hooks origin/reaction-project-hooks && cd ..`
6. `make`

This should launch all the projects. The first launch may take some time. Meteor is in there.

You can `cd` into each child directory and control the project with Docker as usual. The `reaction-next` Makefile is using Docker, too. 

## Platform Support

📓 These scripts (and the reaction-next project) are portable bash. I doubt they'll work in Windows. We can push windows support to a future effort.

---

(I know we're moving away from `reaction-next` terminology. The project name is leftover and has not been renamed yet.)

### CODE REVIEW

**Comment by ticean** [comment]
Ref: https://github.com/reactioncommerce/reaction-next/pull/3

**Comment by aldeed** [comment]
@ticean This is still in In Progress pipeline. Do you want it reviewed yet?

**Comment by spencern** [comment]
@ticean do we need a similar PR in https://github.com/reactioncommerce/reaction?

**Comment by ticean** [comment]
@aldeed Thanks. I missed a workflow step. Yes a review would be much appreciated. 

@spencern yes, we should add a PR to reaction, too. The meta project's not released yet so we'll need to do that to tie it all together.

**Pull request merged**
