### PR TITLE
feat: display order surcharges in UI

### PR DESCRIPTION
**Pull request by kieckhafer**
Must be merged at the same time as of after https://github.com/reactioncommerce/reaction/pull/4829

Impact: **minor**
Type: **feature**

## Issue
We've added the ability to have surcharges attached to an order. This PR displays the surcharges in the UI. Depends on the updates in https://github.com/reactioncommerce/reaction/pull/4829

## Solution
Retrieve surcharge data, and display in Starterkit UI.

## Breaking changes
None

## Testing
1. Add product to cart that has surcharges attached (see https://github.com/reactioncommerce/reaction/pull/4829 for details on adding surcharges)
1. See that surcharges are displayed in checkout, and that you can complete an order

### CODE REVIEW

**Comment by kieckhafer** [comment]
@impactmass This PR goes along with the one in the core app. This one should not be merged until after https://github.com/reactioncommerce/reaction/pull/4829 is merged.

**Comment by kieckhafer** [comment]
@aldeed I've made the change we discussed about displaying a `-` for still calculating surcharges inside the component library: https://github.com/reactioncommerce/reaction-component-library/pull/389

**Comment by aldeed** [comment]
@kieckhafer Needs merge and fix conflicts

**Comment by kieckhafer** [comment]
@aldeed Updated

**Pull request merged**
