### PR TITLE
feat: Open mini-cart on add to cart

### LINKED ISSUE #255: Add-to-cart desktop notification
## Issue

Adding items to cart when in desktop mode has no notification.

## Solution

Open the mini-cart when the user adds an item to the cart

### PR DESCRIPTION
**Pull request by mikemurray**
Resolves #255
Impact: **minor**
Type: **feature**

## Issue

Open the mini-cart when the add to cart button is clicked

## Solution

- Move cart state management to the `uiStore`
- Open the cart using the `uiStore`, close it on a delay

## Breaking changes

none

### Desktop

1. Hover over the cart icon, it should open
1. Move the mouse away from the cart, it should close in 500ms (quickly)
1. Add an item to the cart, see the mini-cart open
1. Mini-cart should close after 3 seconds (so... not so quickly)
1. Add another item to the cart
1. Mouse over the mini-cart before it closes
1. The mini-cart should **not** close after 3 seconds
1. Mouse off of the mini-cart
1. The mini-cart should close in 500ms

### Mobile

1. Resize the window to a mobile size
1. Add an item to the cart
1. You should still see the mobile add to cart slide-out and no mini-cart

### CODE REVIEW

**Comment by willopez** [comment]
Testing with the latest updates to the `GraphQL` API on reaction branch: feat-4577-aldeed-graphql-order-creation

And getting the following error when clicking on the "Add to cart" button:
```
[GraphQL error]: Message: Cannot query field "payments" on type "Checkout"., Location: [{"line":136,"column":5}], Path: undefined
```

**Comment by willopez** [comment]
You'll need to update your docker network name as seen in `.env.example`

**Comment by mikemurray** [comment]
@willopez Does this PR work with the current `1.17.0` branch? It was not built to be tested with `feat-4577-aldeed-graphql-order-creation`. No changes were made to the how items were added to the cart so any bugs related to that branch in reaction should be addressed by another ticket and PR.

**Comment by willopez** [comment]
@mikemurray OK, I'll test it with release 1.17.0

**Comment by willopez** [comment]
@mikemurray Tested with release 1.17.0, it looks good  👍

**Pull request merged**
