### PR TITLE
fix(buttons): WIP - disable ripple on buttons everywhere, add focus style

### LINKED ISSUE #328: Bug: Disable the Material UI button ripple, everywhere
Disable the ripple on:
- Navigation item button
- Profile button
- Profile: Sign in button
- Profile: Create account button
- Profile: Sign out button
- Cart button

PDP
- Add to cart
- `+` button
- `-` button

### PR DESCRIPTION
**Pull request by machikoyasuda**
Resolves #328
Impact: **minor**
Type: **style**

## Issue
Our official style is to _not_ have any Material UI button ripples anywhere.

## Solution

Disabled the ripple on:

1. Navigation item button
2. Profile button
3. Profile: Sign in button
4. Profile: Create account button
5. Profile: Sign out button
6. Cart button

PDP

1. Add to cart
2. `+` button
3. `-` button

## Testing
1. Test nav, both signed in and signed out
2. Test PDP

### CODE REVIEW

**Comment by mikemurray** [comment]
@nnnnat when testing could you verify that these buttons have focus rings when tabbing through the app. If they do not, then that should also be addressed as an accessibility concern.

**Comment by willopez** [comment]
The best way to accomplish this is to create a wrapper component, for example, create a wrapper `Button` component in the starter kit and pass the disable prop to the wrapped component. See: https://material-ui.com/getting-started/faq/#how-can-i-disable-the-ripple-effect-on-the-whole-app-

**Comment by machikoyasuda** [comment]
Confirmed - adding `disableRipple` makes the button focus invisible. Thanks for the catch @mikemurray 👍 I'm going to update this ticket to include 1) adding a wrapper to `disableRipple` and also 2) adding a focus style to that wrapper.

**Comment by machikoyasuda** [comment]
Closing for now

**Comment by spencern** [comment]
Disconnecting this so that it no longer appears in progress.

**Pull request closed without merging**
