### PR TITLE
fix: image grid sizing issue

### PR DESCRIPTION
**Pull request by kieckhafer**
Fixes Issues #65 & #71 

Product grid items have three different sizes. The heights of medium and large items were affecting the grid heights, as there were not stable. In addition, there was no container, so the grid was always full-width

This PR adds a fixed height to product grid images, to keep the grid... a grid. It also adds a 1440px container, as discussed in ticket #71, to contain the grid.

It uses `material-ui-next`s built in CSS-in-JS `sm`, `md`, and `lg` breakpoints.

The PR also adds some docs (a link to the actual Material UI docs).

This PR also removes leftover test code from #59

### CODE REVIEW

**Comment by kieckhafer** [comment]
@rymorgan just want to confirm that we aren't currently doing the three sizes on the grid, and we might save that for future development?

**Comment by kieckhafer** [comment]
@nnnnat if we aren't using the three different sizes anymore, most of this PR is probably not useful.

We should probably keep the container style, but I'm thinking i'll probably get rid of all the style concerning the images in the grid.

Does that sound right?

**Comment by nnnnat** [comment]
@kieckhafer  yeah I think works. 
Sorry about the moving target

**Comment by rymorgan** [comment]
@kieckhafer yep confirmed. We're going to save that feature for a merchanding page functionality in the future

**Pull request merged**
