### PR TITLE
(feat): New Profile Orders page

### LINKED ISSUE #245: Profile address book page
# Work
Create the profile address book page in starter kit

## Route
`/profile/address`

## Permissions
Show blank/404 if not logged in

## Components
- The left sidebar should be a separate component, which will be shared among all of the profile pages. For now, it only needs the account profile section on top and a single "Address book" menu item.
- The right side should have the AddressBook component from the component library.

## Design
https://zpl.io/2vYPqk7

### Loading
Show a loading page spinner while the data is loading.

### PR DESCRIPTION
**Pull request by kieckhafer**
Expands upon #499 to add Orders data to profile page
Impact: **minor**
Type: **feature**

## Issue
Add Orders data to Account Profile

## Solution
- Split existing orders page into `profileAddressBook` and `profileOrders` pages. This is necessary due to the way we do pagination, our existing method broke when using `asPath` to display different components (`Orders` or `AddressBook`) on a single page based on the URL.

## Breaking changes
None

## Testing

- Visit `/profile/orders` as a non-logged in user, and see a 404 / page not found
- Login as a user, create 6+ orders (to see pagination)
- Visit `/profile/orders` as a logged in user, see that orders show up and match our designs: https://zpl.io/V0ypYWR
- Move orders into different workflow statuses
- See orders are filtered as they should

### CODE REVIEW

**Comment by zenweasel** [comment]
@kieckhafer @dancastellon So who is going to carry this forward? Can we review and merge?

**Comment by kieckhafer** [comment]
Booted it up, looks good to me / works as described in @dancastellon's comment. 

Happy to merge if that's ok, However... maybe someone who wasn't involved should take a look for a code review.

**Comment by nnnnat** [comment]
Awesome @dancastellon !!! I agree with @kieckhafer maybe having @mikemurray or @willopez do a quick code review / smoke test then merge this bad boi. I think the code is looking good but I've not run it

**Comment by rymorgan** [comment]
@kieckhafer The forms are too wide (waf). Can y'al reduce the max width to around 900px.

**Comment by rymorgan** [comment]
After some internal discussion I realized my comments weren't exactly clear. The intention for the designs on both the address book and are to have the spacing work like this <1><3><7><1> -- the <3> is for the in page navigation "Order history" and "Address book". <7> for the form elements and the main column. The <1>'s are extra space on the margins and will also center smaller content on the page.  https://app.zeplin.io/project/5afc82f5e8d73e250ff9d855/dashboard?seid=5b19637b463238c438791b8c

**Comment by kieckhafer** [comment]
@dancastellon @nnnnat just FYI I created a new PR, #499, that had all the changes that were done by you two (and myself), which was just merged, and I'm using this PR to expand and do the Orders part of the profile. So if / when the time comes, ignore all the above comments about the three of us not reviewing this PR.

**Comment by kieckhafer** [comment]
Comments here related to an older branch that was merged already. Closing in favor of #507 to get a clean slate for this review.

**Pull request closed without merging**
